package com.ensa.ged.model;

// Generated Jun 19, 2014 11:39:07 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Convention generated by hbm2java
 */
@Entity
@Table(name = "Convention", catalog = "GED_DB2")
public class Convention implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String titre;
	private Date debut;
	private Date fin;
	private String obligationMuni;
	private Set<Objectif> objectifses = new HashSet<Objectif>(0);
	private Set<Membre> membres = new HashSet<Membre>(0);

	public Convention() {
	}

	public Convention(long id) {
		this.id = id;
	}

	public Convention(long id, String titre, Date debut, Date fin,
			String obligationMuni, Set<Objectif> objectifses, Set<Membre> membres) {
		this.id = id;
		this.titre = titre;
		this.debut = debut;
		this.fin = fin;
		this.obligationMuni = obligationMuni;
		this.objectifses = objectifses;
		this.membres = membres;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "titre", length = 254)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "debut", length = 19)
	public Date getDebut() {
		return this.debut;
	}

	public void setDebut(Date debut) {
		this.debut = debut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fin", length = 19)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@Column(name = "obligationMuni", length = 254)
	public String getObligationMuni() {
		return this.obligationMuni;
	}

	public void setObligationMuni(String obligationMuni) {
		this.obligationMuni = obligationMuni;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "convention",cascade = {CascadeType.ALL})
	public Set<Objectif> getObjectifses() {
		return this.objectifses;
	}

	public void setObjectifses(Set<Objectif> objectifses) {
		this.objectifses = objectifses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "convention",cascade = {CascadeType.ALL})
	public Set<Membre> getMembres() {
		return this.membres;
	}

	public void setMembres(Set<Membre> membres) {
		this.membres = membres;
	}

}
