package com.ensa.ged.model;

// Generated Jun 19, 2014 11:39:07 PM by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Decison generated by hbm2java
 */
@Entity
@Table(name = "Decison", catalog = "GED_DB2")
public class Decison implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private Autorisation autorisation;
	private String decision;

	public Decison() {
	}

	public Decison(long id, Autorisation autorisation) {
		this.id = id;
		this.autorisation = autorisation;
	}

	public Decison(long id, Autorisation autorisation, String decision) {
		this.id = id;
		this.autorisation = autorisation;
		this.decision = decision;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = {CascadeType.ALL})
	@JoinColumn(name = "Aut_id", nullable = false)
	public Autorisation getAutorisation() {
		return this.autorisation;
	}

	public void setAutorisation(Autorisation autorisation) {
		this.autorisation = autorisation;
	}

	@Column(name = "decision", length = 254)
	public String getDecision() {
		return this.decision;
	}

	public void setDecision(String decision) {
		this.decision = decision;
	}

}
