package com.ensa.ged.model;

// Generated Jun 19, 2014 11:39:07 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Membre generated by hbm2java
 */
@Entity
@Table(name = "Membre", catalog = "GED_DB2")
public class Membre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private Convention convention;
	private String nom;
	private Set<Obligation> obligations = new HashSet<Obligation>(0);
	
	
	
	
	
	public List<Obligation> obligationList(){
		List<Obligation> list=new ArrayList<>();
		
		
		for(Obligation o: obligations){
			list.add(o);
			
		}
		
		return list;
	}
	
	public Membre() {
	}

	public Membre(long id, Convention convention) {
		this.id = id;
		this.convention = convention;
	}

	public Membre(long id, Convention convention, String nom, Set<Obligation> obligations) {
		this.id = id;
		this.convention = convention;
		this.nom = nom;
		this.obligations = obligations;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = {CascadeType.ALL})
	@JoinColumn(name = "Con_id", nullable = false)
	public Convention getConvention() {
		return this.convention;
	}

	public void setConvention(Convention convention) {
		this.convention = convention;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membre",cascade = {CascadeType.ALL})
	public Set<Obligation> getObligations() {
		return this.obligations;
	}

	public void setObligations(Set<Obligation> obligations) {
		this.obligations = obligations;
	}

}
