package com.ensa.ged.model;

// Generated Jun 19, 2014 11:39:07 PM by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Objectifs generated by hbm2java
 */
@Entity
@Table(name = "Objectifs", catalog = "GED_DB2")
public class Objectif implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private Convention convention;
	private String objectif;

	public Objectif() {
	}

	public Objectif(long id, Convention convention) {
		this.id = id;
		this.convention = convention;
	}

	public Objectif(long id, Convention convention, String objectif) {
		this.id = id;
		this.convention = convention;
		this.objectif = objectif;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = {CascadeType.ALL})
	@JoinColumn(name = "Con_id", nullable = false)
	public Convention getConvention() {
		return this.convention;
	}

	public void setConvention(Convention convention) {
		this.convention = convention;
	}

	@Column(name = "objectif", length = 254)
	public String getObjectif() {
		return this.objectif;
	}

	public void setObjectif(String objectif) {
		this.objectif = objectif;
	}

}
