package com.ensa.ged.model;

// Generated Jun 19, 2014 11:39:07 PM by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Obligation generated by hbm2java
 */
@Entity
@Table(name = "Obligation", catalog = "GED_DB2")
public class Obligation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private Membre membre;
	private String obligation;

	public Obligation() {
	}

	public Obligation(long id, Membre membre) {
		this.id = id;
		this.membre = membre;
	}

	public Obligation(long id, Membre membre, String obligation) {
		this.id = id;
		this.membre = membre;
		this.obligation = obligation;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = {CascadeType.ALL})
	@JoinColumn(name = "Mem_id", nullable = false)
	public Membre getMembre() {
		return this.membre;
	}

	public void setMembre(Membre membre) {
		this.membre = membre;
	}

	@Column(name = "obligation", length = 254)
	public String getObligation() {
		return this.obligation;
	}

	public void setObligation(String obligation) {
		this.obligation = obligation;
	}

}
