package com.ensa.ged.model;

// Generated Jun 19, 2014 11:39:07 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name = "Personne", catalog = "GED_DB2")
public class Personne implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nom;
	private String occupation;
	private Set<Autorisation> autorisations = new HashSet<Autorisation>(0);

	public Personne() {
	}

	public Personne(int id) {
		this.id = id;
	}

	public Personne(int id, String nom, String occupation, Set<Autorisation> autorisations) {
		this.id = id;
		this.nom = nom;
		this.occupation = occupation;
		this.autorisations = autorisations;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "occupation", length = 254)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personne")
	public Set<Autorisation> getAutorisations() {
		return this.autorisations;
	}

	public void setAutorisations(Set<Autorisation> autorisations) {
		this.autorisations = autorisations;
	}

}
