package com.ensa.ged.model;

// Generated Jun 18, 2014 11:36:08 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Repertory generated by hbm2java
 */
@Entity
@Table(name = "Repertory", catalog = "GED_DB2")
public class Repertory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idRepertory;
	
	private String nameRepertory;
	private Set<SousRepertory> sousRepertories = new HashSet<SousRepertory>(0);
	private Set<Document> documents = new HashSet<Document>(0);

	public Repertory() {
	}

	public Repertory(long idRepertory) {
		this.idRepertory = idRepertory;
	}

	public Repertory(long idRepertory,
			String nameRepertory, Set<SousRepertory> sousRepertories, Set<Document> documents) {
		this.idRepertory = idRepertory;
		
		this.nameRepertory = nameRepertory;
		this.sousRepertories = sousRepertories;
		this.documents = documents;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "idRepertory", unique = true, nullable = false)
	public long getIdRepertory() {
		return this.idRepertory;
	}

	public void setIdRepertory(long idRepertory) {
		this.idRepertory = idRepertory;
	}

	@Column(name = "nameRepertory", length = 254)
	public String getNameRepertory() {
		return this.nameRepertory;
	}

	public void setNameRepertory(String nameRepertory) {
		this.nameRepertory = nameRepertory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repertory" ,cascade = {CascadeType.ALL})
	public Set<SousRepertory> getSousRepertories() {
		return this.sousRepertories;
	}

	public void setSousRepertories(Set<SousRepertory> sousRepertories) {
		this.sousRepertories = sousRepertories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repertory",cascade = {CascadeType.ALL})
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
