package com.ensa.ged.model;

// Generated Jun 18, 2014 11:36:08 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "Roles", catalog = "GED_DB2")
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long roleId;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public Roles() {
	}

	public Roles(long roleId, String name) {
		this.roleId = roleId;
		this.name = name;
	}

	public Roles(long roleId, String name, Set<User> users) {
		this.roleId = roleId;
		this.name = name;
		this.users = users;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "roleId", unique = true, nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY , cascade = {CascadeType.ALL})
	@JoinTable(name = "USER_ROLE", catalog = "GED_DB2", joinColumns = { @JoinColumn(name = "roles_roleId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "userlist_userID", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
