package com.ensa.ged.model;

// Generated Jun 18, 2014 11:36:08 PM by Hibernate Tools 4.0.0

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TextPrivate generated by hbm2java
 */
@Entity
@Table(name = "TextPrivate", catalog = "GED_DB2")
public class TextPrivate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idTexPriv;
	private Document document;
	private String titreTextPriv;

	public TextPrivate() {
	}

	public TextPrivate(long idTexPriv, Document document) {
		this.idTexPriv = idTexPriv;
		this.document = document;
	}

	public TextPrivate(long idTexPriv, Document document, String titreTextPriv) {
		this.idTexPriv = idTexPriv;
		this.document = document;
		this.titreTextPriv = titreTextPriv;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "idTexPriv", unique = true, nullable = false)
	public long getIdTexPriv() {
		return this.idTexPriv;
	}

	public void setIdTexPriv(long idTexPriv) {
		this.idTexPriv = idTexPriv;
	}

	@ManyToOne(fetch = FetchType.LAZY ,cascade = {CascadeType.ALL})
	@JoinColumn(name = "idDocument", nullable = false)
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	@Column(name = "titreTextPriv", length = 254)
	public String getTitreTextPriv() {
		return this.titreTextPriv;
	}

	public void setTitreTextPriv(String titreTextPriv) {
		this.titreTextPriv = titreTextPriv;
	}

}
