package com.ensa.ged.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "Document", catalog = "GED_DB")
public class Document implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idDocument;
	private Repertory repertory;
	private Groupe groupe;
	private User user;
	private TypeDocument typeDocument;
	private String themeDoc;
	private String titre;
	private Date dateEdition;
	private Date dateMiseAjour;
	private Date dateIncertion;
	private Integer tailleDoc;
	private Set<History> histories = new HashSet<History>(0);
	private Set<TextPublic> textPublics = new HashSet<TextPublic>(0);
	private Set<MotCle> motCles = new HashSet<MotCle>(0);
	private Set<TextPrivate> textPrivates = new HashSet<TextPrivate>(0);

	public Document() {
	}

	public Document(long idDocument, Repertory repertory, User user,
			TypeDocument typeDocument) {
		this.idDocument = idDocument;
		this.repertory = repertory;
		this.user = user;
		this.typeDocument = typeDocument;
	}

	public Document(long idDocument, Repertory repertory, Groupe groupe,
			User user, TypeDocument typeDocument, String themeDoc,
			String titre, Date dateEdition, Date dateMiseAjour,
			Date dateIncertion, Integer tailleDoc, Set<History> histories,
			Set<TextPublic> textPublics, Set<MotCle> motCles, Set<TextPrivate> textPrivates) {
		this.idDocument = idDocument;
		this.repertory = repertory;
		this.groupe = groupe;
		this.user = user;
		this.typeDocument = typeDocument;
		this.themeDoc = themeDoc;
		this.titre = titre;
		this.dateEdition = dateEdition;
		this.dateMiseAjour = dateMiseAjour;
		this.dateIncertion = dateIncertion;
		this.tailleDoc = tailleDoc;
		this.histories = histories;
		this.textPublics = textPublics;
		this.motCles = motCles;
		this.textPrivates = textPrivates;
	}

	@Id
	@Column(name = "idDocument", unique = true, nullable = false)
	public long getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(long idDocument) {
		this.idDocument = idDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRepertory", nullable = false)
	public Repertory getRepertory() {
		return this.repertory;
	}

	public void setRepertory(Repertory repertory) {
		this.repertory = repertory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGroupe")
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTypeDoc", nullable = false)
	public TypeDocument getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(TypeDocument typeDocument) {
		this.typeDocument = typeDocument;
	}

	@Column(name = "themeDoc", length = 20)
	public String getThemeDoc() {
		return this.themeDoc;
	}

	public void setThemeDoc(String themeDoc) {
		this.themeDoc = themeDoc;
	}

	@Column(name = "titre", length = 254)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateEdition", length = 19)
	public Date getDateEdition() {
		return this.dateEdition;
	}

	public void setDateEdition(Date dateEdition) {
		this.dateEdition = dateEdition;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateMiseAjour", length = 19)
	public Date getDateMiseAjour() {
		return this.dateMiseAjour;
	}

	public void setDateMiseAjour(Date dateMiseAjour) {
		this.dateMiseAjour = dateMiseAjour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateIncertion", length = 19)
	public Date getDateIncertion() {
		return this.dateIncertion;
	}

	public void setDateIncertion(Date dateIncertion) {
		this.dateIncertion = dateIncertion;
	}

	@Column(name = "tailleDoc")
	public Integer getTailleDoc() {
		return this.tailleDoc;
	}

	public void setTailleDoc(Integer tailleDoc) {
		this.tailleDoc = tailleDoc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "document")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "document")
	public Set<TextPublic> getTextPublics() {
		return this.textPublics;
	}

	public void setTextPublics(Set<TextPublic> textPublics) {
		this.textPublics = textPublics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "document")
	public Set<MotCle> getMotCles() {
		return this.motCles;
	}

	public void setMotCles(Set<MotCle> motCles) {
		this.motCles = motCles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "document")
	public Set<TextPrivate> getTextPrivates() {
		return this.textPrivates;
	}

	public void setTextPrivates(Set<TextPrivate> textPrivates) {
		this.textPrivates = textPrivates;
	}

}
