package com.ensa.ged.model;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "Groupe", catalog = "GED_DB")
public class Groupe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idGroupe;
	private String nameGroupe;
	private Set<Document> documents = new HashSet<Document>(0);

	public Groupe() {
	}

	public Groupe(long idGroupe) {
		this.idGroupe = idGroupe;
	}

	public Groupe(long idGroupe, String nameGroupe, Set<Document> documents) {
		this.idGroupe = idGroupe;
		this.nameGroupe = nameGroupe;
		this.documents = documents;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "idGroupe", unique = true, nullable = false)
	public long getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(long idGroupe) {
		this.idGroupe = idGroupe;
	}

	@Column(name = "nameGroupe", length = 254)
	public String getNameGroupe() {
		return this.nameGroupe;
	}

	public void setNameGroupe(String nameGroupe) {
		this.nameGroupe = nameGroupe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
