package com.ensa.ged.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "History", catalog = "GED_DB")
public class History implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idHistory;
	private Document document;
	private Date dateHistory;
	private String nameUser;
	private String cniUser;

	public History() {
	}

	public History(long idHistory, Document document) {
		this.idHistory = idHistory;
		this.document = document;
	}

	public History(long idHistory, Document document, Date dateHistory,
			String nameUser, String cniUser) {
		this.idHistory = idHistory;
		this.document = document;
		this.dateHistory = dateHistory;
		this.nameUser = nameUser;
		this.cniUser = cniUser;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "idHistory", unique = true, nullable = false)
	public long getIdHistory() {
		return this.idHistory;
	}

	public void setIdHistory(long idHistory) {
		this.idHistory = idHistory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocument", nullable = false)
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateHistory", length = 19)
	public Date getDateHistory() {
		return this.dateHistory;
	}

	public void setDateHistory(Date dateHistory) {
		this.dateHistory = dateHistory;
	}

	@Column(name = "nameUser", length = 254)
	public String getNameUser() {
		return this.nameUser;
	}

	public void setNameUser(String nameUser) {
		this.nameUser = nameUser;
	}

	@Column(name = "cniUser", length = 254)
	public String getCniUser() {
		return this.cniUser;
	}

	public void setCniUser(String cniUser) {
		this.cniUser = cniUser;
	}

}
