package com.ensa.ged.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Repertory generated by hbm2java
 */
@Entity
@Table(name = "Repertory", catalog = "GED_DB")
public class Repertory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idRepertory;
	private String nameRepertory;
	private Date dateCreation;
	private Date dateUpdate;
	private Set<Document> documents = new HashSet<Document>(0);
	private Set<SousRepertory> sousRepertories = new HashSet<SousRepertory>(0);

	public Repertory() {
	}

	public Repertory(long idRepertory) {
		this.idRepertory = idRepertory;
	}

	public Repertory(long idRepertory, String nameRepertory, Date dateCreation,
			Date dateUpdate, Set<Document> documents, Set<SousRepertory> sousRepertories) {
		this.idRepertory = idRepertory;
		this.nameRepertory = nameRepertory;
		this.dateCreation = dateCreation;
		this.dateUpdate = dateUpdate;
		this.documents = documents;
		this.sousRepertories = sousRepertories;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "idRepertory", unique = true, nullable = false)
	public long getIdRepertory() {
		return this.idRepertory;
	}

	public void setIdRepertory(long idRepertory) {
		this.idRepertory = idRepertory;
	}

	@Column(name = "nameRepertory", length = 254)
	public String getNameRepertory() {
		return this.nameRepertory;
	}

	public void setNameRepertory(String nameRepertory) {
		this.nameRepertory = nameRepertory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateUpdate", length = 19)
	public Date getDateUpdate() {
		return this.dateUpdate;
	}

	public void setDateUpdate(Date dateUpdate) {
		this.dateUpdate = dateUpdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repertory")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "repertory")
	public Set<SousRepertory> getSousRepertories() {
		return this.sousRepertories;
	}

	public void setSousRepertories(Set<SousRepertory> sousRepertories) {
		this.sousRepertories = sousRepertories;
	}

}
