package com.ensa.ged.model;
 
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Roles generated by hbm2java 
 */
@Entity
@Table(name = "Roles", catalog = "GED_DB")
public class Roles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long roleId;
	private String name;

	
	private Set<User> userlist;

	/**
	 * @return the user
	 */
	@ManyToMany(mappedBy ="roles")
	public Set<User> getUserlist() {
		return userlist;
	}

	/**
	 * @param user
	 *            the user to set
	 */
	public void setUserlist(Set<User> user) {
		this.userlist = user;
	}

	public Roles() {
	}

	public Roles(long roleId, String name) {
		this.roleId = roleId;
		this.name = name;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "roleId", unique = true, nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
