package com.ensa.ged.model;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "GED_DB")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long userId;
	private String userName;
	private String emailUser;
	
	private String cniUser;
	private String nationUser;
	private String professionUser;
	private String pwdUser;
	private Set<Document> documents = new HashSet<Document>(0);
	
	
	private boolean enabled;
	
	
	
   
	private Set<Roles> roles;
	

	/**
	 * @return the roles
	 * 
	 */
	@ManyToMany
	@JoinTable(name = "USER_ROLE")
	public Set<Roles> getRoles() {
		return roles;
	}

	/**
	 * @param roles the roles to set
	 */
	public void setRoles(Set<Roles> roles) {
		this.roles = roles;
	}

	public User() {
	}

	public User(long userId) {
		this.userId = userId;
	}

	public User(long userId, String userName, String emailUser, String cniUser,
			String nationUser, String professionUser, String pwdUser,
			Set<Document> documents) {
		this.userId = userId;
		this.userName = userName;
		this.emailUser = emailUser;
		this.cniUser = cniUser;
		this.nationUser = nationUser;
		this.professionUser = professionUser;
		this.pwdUser = pwdUser;
		this.documents = documents;
	}

	@Id
	@GenericGenerator(name="incr" , strategy="increment")
	@GeneratedValue(generator="incr")
	@Column(name = "userID", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "userName", length = 254)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "emailUser", length = 20)
	public String getEmailUser() {
		return this.emailUser;
	}

	public void setEmailUser(String emailUser) {
		this.emailUser = emailUser;
	}

	@Column(name = "cniUser", length = 254)
	public String getCniUser() {
		return this.cniUser;
	}

	public void setCniUser(String cniUser) {
		this.cniUser = cniUser;
	}

	@Column(name = "nationUser", length = 254)
	public String getNationUser() {
		return this.nationUser;
	}

	public void setNationUser(String nationUser) {
		this.nationUser = nationUser;
	}

	@Column(name = "professionUser", length = 254)
	public String getProfessionUser() {
		return this.professionUser;
	}

	public void setProfessionUser(String professionUser) {
		this.professionUser = professionUser;
	}

	@Column(name = "pwdUser", length = 254)
	public String getPwdUser() {
		return this.pwdUser;
	}

	public void setPwdUser(String pwdUser) {
		this.pwdUser = pwdUser;
	}

	@OneToMany( fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
